name: EyeHeadCoupling
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - ipykernel
  - jupyterlab
  - ipympl
  - pyqt
  - openjpeg=2.5.2
  - libtiff>=4.5.0,<4.7.0
  - pip
  - pip:
      - anyio
      - httpx
      - beautifulsoup4
